site_name: ruptures
repo_url: https://github.com/deepcharles/ruptures
docs_dir: docs
site_dir: site
plugins:
  - search
  - mkdocstrings:
      watch:
        - ruptures
      handlers:
        python:
          selection:
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
  - nbconvert:
      input_dir: notebooks
      output_dir: notebooks
      recursive: true
markdown_extensions:
  - pymdownx.snippets:
  - pymdownx.tabbed:
  - pymdownx.emoji:
  - pymdownx.superfences:
  - pymdownx.arithmatex:
      generic: true
  - admonition:
  - toc:
      permalink: "#"
nav:
  - Home:
    - 'Welcome to ruptures': index.md
  - Getting started:
    - 'Change point detection?': what-is-cpd.md
    - 'Installation': install.md
    - 'Basic usage': notebooks/basic-usage.md
    - 'Fitting and predicting': fit-and-predict.md
    - 'Custom cost function': custom-cost-function.md
  - User guide:
    - 'Introduction': user-guide/index.md
    - 'Search methods': user-guide/search-methods.md
    - Cost functions:
      - 'CostL1': user-guide/cost-functions/costl1.md
      - 'CostL2': user-guide/cost-functions/costl2.md
      - 'CostNormal': user-guide/cost-functions/costnormal.md
      - 'CostRbf': user-guide/cost-functions/costrbf.md
      - 'CostLinear': user-guide/cost-functions/costlinear.md
      - 'CostRank': user-guide/cost-functions/costrank.md
      - 'CostMl': user-guide/cost-functions/costml.md
      - 'CostAR': user-guide/cost-functions/costautoregressive.md
      - 'Custom cost': user-guide/cost-functions/costcustom.md
    - 'Generate signals': user-guide/generate-signals.md
    - 'Evaluation and visualizations': user-guide/evaluation.md
  - Gallery of examples:
    - 'Simple example': notebooks/simple-example.md
  - Code Reference:
      - Base: code-reference/base-reference.md
      - Costs:
          - 'CostL1': code-reference/costs/costl1-reference.md
          - 'CostL2': code-reference/costs/costl2-reference.md
          - 'CostNormal': code-reference/costs/costnormal-reference.md
          - 'CostRbf': code-reference/costs/costrbf-reference.md
          - 'CostLinear': code-reference/costs/costlinear-reference.md
          - 'CostRank': code-reference/costs/costrank-reference.md
          - 'CostMl': code-reference/costs/costml-reference.md
          - CostAR: code-reference/costs/costautoregressive-reference.md
      - Detection:
          - Binseg: code-reference/detection/binseg-reference.md
          - BottomUp: code-reference/detection/bottomup-reference.md
          - Dynp: code-reference/detection/dynp-reference.md
          - GreedyAR: code-reference/detection/greedyar-reference.md
          - GreedyLinear: code-reference/detection/greedylinear-reference.md
          - Omp: code-reference/detection/omp-reference.md
          - OmpK: code-reference/detection/ompk-reference.md
          - Pelt: code-reference/detection/pelt-reference.md
          - Window: code-reference/detection/window-reference.md
      - Datasets: code-reference/datasets/datasets-reference.md
  - About:
    - 'Release notes': release-notes.md
    - 'Contributing': contributing.md
    - 'License': license.md
theme:
  name: material
  features:
    - navigation.tabs
    - search.highlight
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js