name: "Pull Request Docs Check"
on: 
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
